version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sja-postgres
    environment:
      POSTGRES_DB: sjadb
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      network: host
      dockerfile: Dockerfile
    container_name: sja-backend
    environment:
      DATABASE_URL: postgresql://dev:dev@localhost:5432/sjadb
      SERVER_URL: localhost
      SERVER_PORT: 3001
    depends_on:
      - postgres
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sja-frontend
    environment:
      BACKEND_API: http://localhost:3001/api
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
